[package]
name = "ProjetAnnuel"
version = "0.1.2"
edition = "2024"

[lib]
name = "projetannuel"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version= "0.24.0", features = ["extension-module"] }
rand = "*"
rand_distr = "*"
osqp = "0.6"


