[package]
name = "ProjetAnnuel"
version = "0.1.0"
edition = "2021"

[lib]
name = "projetannuel"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version= "0.24.0", features = ["extension-module"] }
rand = "*"

